# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 08:29


from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Title of the talk', max_length=200)),
                ('description', models.CharField(help_text='Description of the talk', max_length=1000)),
                ('location', models.CharField(help_text='Location of talk', max_length=200)),
                ('time', models.DateTimeField(help_text='Time when talk was or will be presented')),
                ('presenters',
                 models.ManyToManyField(help_text='The presenters of the talk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
